---
- hosts: all
  tasks:

  - name: copy dockerfile into Remote machine
    copy:
     src: dockerfile
     dest: .

  - name: copy .war file into Remote machine
    copy:
     src: webapp.war
     dest: .

  - name: stop the running container
    command: docker stop phyzo-con
    ignore_errors: True

  - name: remove the running container
    command: docker rm phyzo-con
    ignore_errors: True

  - name: remove the running image
    command: docker rmi phyzo-im
    ignore_errors: True

  - name: create customimage from dockerfile 
    command: docker build -t phyzo-im .
     
  - name: create and run container
    command: docker run -d --name phyzo-con -p 8080:8080 phyzo-im
